### ISSUE TITLE
eclipse.copilot will not provide ghost text

### ISSUE THREAD

**Issue by vgcpge** [equodev/eclipse-ai-example#5]
UI contributions are out of scope for eclipse.copilot. Ghost text will have to be supported either in Eclipse Core text editing APIs or in LSP4E. eclipse.copilot is just another language server LSP4E makes use of.

**Comment by nedtwigg** [comment]
Thanks for the info! Just curious, have you used the "ghost text" interface in any context? Do you prefer the standard suggestion box that Eclipse core has used?

I ask because I really like the ghost text, but I have never tried using an LLM-autocompleter except through ghost text.

**Comment by vgcpge** [comment]
Ghost text is just another suggestion option. I agree it is visually appealing, but do not have a strong preference.
The alternative is iitelli-sense style of suggestions, that shows more variants at once.
